### ISSUE TITLE
Content model with location field

### ISSUE THREAD

**Issue by martinholmin** [contentful-labs/contentful_middleman#12]
I just started playing around with a content model including a location field. Trying to import data throws the following error `can't dump anonymous class: Contentful::DynamicEntry[4LCKv2iJxSMacAQ62gWeeQ] (TypeError)`. 

I'm about to start digging deeper, but I just wanted to check if it might be a beginners mistake. 

My config block looks like this:
```ruby
activate :contentful do |f|
  f.space         = {frogtail: ENV['CONTENTFUL_SPACE']}
  f.access_token  = ENV['CONTENTFUL_TOKEN']
  f.cda_query     = { content_type: '2EJwHfAkM46k6KKkYo6ace'}
  f.content_types = { simple: '2EJwHfAkM46k6KKkYo6ace'}
end
```

Any help is greatly appreciated

Full stack trace:

```sh
/Users/mholmin/.rbenv/versions/2.1.5/lib/ruby/2.1.0/psych/visitors/yaml_tree.rb:329:in `visit_Class': can't dump anonymous class: Contentful::DynamicEntry[4LCKv2iJxSMacAQ62gWeeQ] (TypeError)
	from /Users/mholmin/.rbenv/versions/2.1.5/lib/ruby/2.1.0/psych/visitors/yaml_tree.rb:148:in `accept'
	from /Users/mholmin/.rbenv/versions/2.1.5/lib/ruby/2.1.0/psych/visitors/yaml_tree.rb:349:in `block in visit_Hash'
	from /Users/mholmin/.rbenv/versions/2.1.5/lib/ruby/2.1.0/psych/visitors/yaml_tree.rb:347:in `each'
	from /Users/mholmin/.rbenv/versions/2.1.5/lib/ruby/2.1.0/psych/visitors/yaml_tree.rb:347:in `visit_Hash'
	from /Users/mholmin/.rbenv/versions/2.1.5/lib/ruby/2.1.0/psych/visitors/yaml_tree.rb:148:in `accept'
	from /Users/mholmin/.rbenv/versions/2.1.5/lib/ruby/2.1.0/psych/visitors/yaml_tree.rb:516:in `block in dump_ivars'
	from /Users/mholmin/.rbenv/versions/2.1.5/lib/ruby/2.1.0/psych/visitors/yaml_tree.rb:514:in `each'
	from /Users/mholmin/.rbenv/versions/2.1.5/lib/ruby/2.1.0/psych/visitors/yaml_tree.rb:514:in `dump_ivars'
	from /Users/mholmin/.rbenv/versions/2.1.5/lib/ruby/2.1.0/psych/visitors/yaml_tree.rb:175:in `visit_Object'
	from /Users/mholmin/.rbenv/versions/2.1.5/lib/ruby/2.1.0/psych/visitors/yaml_tree.rb:148:in `accept'
	from /Users/mholmin/.rbenv/versions/2.1.5/lib/ruby/2.1.0/psych/visitors/yaml_tree.rb:516:in `block in dump_ivars'
	from /Users/mholmin/.rbenv/versions/2.1.5/lib/ruby/2.1.0/psych/visitors/yaml_tree.rb:514:in `each'
	from /Users/mholmin/.rbenv/versions/2.1.5/lib/ruby/2.1.0/psych/visitors/yaml_tree.rb:514:in `dump_ivars'
	from /Users/mholmin/.rbenv/versions/2.1.5/lib/ruby/2.1.0/psych/visitors/yaml_tree.rb:175:in `visit_Object'
	from /Users/mholmin/.rbenv/versions/2.1.5/lib/ruby/2.1.0/psych/visitors/yaml_tree.rb:148:in `accept'
	from /Users/mholmin/.rbenv/versions/2.1.5/lib/ruby/2.1.0/psych/visitors/yaml_tree.rb:349:in `block in visit_Hash'
	from /Users/mholmin/.rbenv/versions/2.1.5/lib/ruby/2.1.0/psych/visitors/yaml_tree.rb:347:in `each'
	from /Users/mholmin/.rbenv/versions/2.1.5/lib/ruby/2.1.0/psych/visitors/yaml_tree.rb:347:in `visit_Hash'
	from /Users/mholmin/.rbenv/versions/2.1.5/lib/ruby/2.1.0/psych/visitors/yaml_tree.rb:148:in `accept'
	from /Users/mholmin/.rbenv/versions/2.1.5/lib/ruby/2.1.0/psych/visitors/yaml_tree.rb:112:in `push'
	from /Users/mholmin/.rbenv/versions/2.1.5/lib/ruby/2.1.0/psych.rb:409:in `dump'
	from /Users/mholmin/.rbenv/versions/2.1.5/lib/ruby/2.1.0/psych/core_ext.rb:14:in `psych_to_yaml'
	from /Users/mholmin/Code/Frogtail/middleman_base/vendor/gems/ruby/2.1.0/gems/contentful_middleman-1.0.2/lib/contentful_middleman/commands/context.rb:64:in `to_yaml'
	from /Users/mholmin/Code/Frogtail/middleman_base/vendor/gems/ruby/2.1.0/gems/contentful_middleman-1.0.2/lib/Contentful_middleman/import_task.rb:34:in `block in local_data_files'
	from /Users/mholmin/Code/Frogtail/middleman_base/vendor/gems/ruby/2.1.0/gems/contentful-0.5.0/lib/contentful/resource/array_like.rb:15:in `each'
	from /Users/mholmin/Code/Frogtail/middleman_base/vendor/gems/ruby/2.1.0/gems/contentful-0.5.0/lib/contentful/resource/array_like.rb:15:in `each_item'
	from /Users/mholmin/Code/Frogtail/middleman_base/vendor/gems/ruby/2.1.0/gems/contentful_middleman-1.0.2/lib/Contentful_middleman/import_task.rb:27:in `map'
	from /Users/mholmin/Code/Frogtail/middleman_base/vendor/gems/ruby/2.1.0/gems/contentful_middleman-1.0.2/lib/Contentful_middleman/import_task.rb:27:in `local_data_files'
	from /Users/mholmin/Code/Frogtail/middleman_base/vendor/gems/ruby/2.1.0/gems/contentful_middleman-1.0.2/lib/Contentful_middleman/import_task.rb:14:in `run'
	from /Users/mholmin/Code/Frogtail/middleman_base/vendor/gems/ruby/2.1.0/gems/contentful_middleman-1.0.2/lib/contentful_middleman/commands/contentful.rb:48:in `block in contentful'
	from /Users/mholmin/Code/Frogtail/middleman_base/vendor/gems/ruby/2.1.0/gems/contentful_middleman-1.0.2/lib/contentful_middleman/commands/contentful.rb:46:in `each'
	from /Users/mholmin/Code/Frogtail/middleman_base/vendor/gems/ruby/2.1.0/gems/contentful_middleman-1.0.2/lib/contentful_middleman/commands/contentful.rb:46:in `reduce'
	from /Users/mholmin/Code/Frogtail/middleman_base/vendor/gems/ruby/2.1.0/gems/contentful_middleman-1.0.2/lib/contentful_middleman/commands/contentful.rb:46:in `contentful'
	from /Users/mholmin/Code/Frogtail/middleman_base/vendor/gems/ruby/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/mholmin/Code/Frogtail/middleman_base/vendor/gems/ruby/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/mholmin/Code/Frogtail/middleman_base/vendor/gems/ruby/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Users/mholmin/Code/Frogtail/middleman_base/vendor/gems/ruby/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Users/mholmin/Code/Frogtail/middleman_base/vendor/gems/ruby/2.1.0/bundler/gems/middleman-eede4a8c5d98/middleman-core/lib/middleman-core/cli.rb:72:in `method_missing'
	from /Users/mholmin/Code/Frogtail/middleman_base/vendor/gems/ruby/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:29:in `run'
	from /Users/mholmin/Code/Frogtail/middleman_base/vendor/gems/ruby/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:126:in `run'
	from /Users/mholmin/Code/Frogtail/middleman_base/vendor/gems/ruby/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/mholmin/Code/Frogtail/middleman_base/vendor/gems/ruby/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Users/mholmin/Code/Frogtail/middleman_base/vendor/gems/ruby/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Users/mholmin/Code/Frogtail/middleman_base/vendor/gems/ruby/2.1.0/bundler/gems/middleman-eede4a8c5d98/middleman-core/lib/middleman-core/cli.rb:20:in `start'
	from /Users/mholmin/Code/Frogtail/middleman_base/vendor/gems/ruby/2.1.0/bundler/gems/middleman-eede4a8c5d98/middleman-core/bin/middleman:18:in `<top (required)>'
	from /Users/mholmin/Code/Frogtail/middleman_base/vendor/gems/ruby/2.1.0/bin/middleman:23:in `load'
	from /Users/mholmin/Code/Frogtail/middleman_base/vendor/gems/ruby/2.1.0/bin/middleman:23:in `<main>'
```

**Comment by madtrick** [comment]
@martinholmin thanks for reporting this. The fix should be soon deployed

**Comment by madtrick** [comment]
@martinholmin could you please update the gem and try again?

**Comment by martinholmin** [comment]
It works fine. Thank you!
