### ISSUE TITLE
'require': cannot load such file -- Contentful_middleman/import_task 

### ISSUE THREAD

**Issue by Naatan** [contentful-labs/contentful_middleman#16]
Line 8 has uppercase character, changing to lowercase fixes it.

```
$ middleman contentful                                                                       [11:09:07]
/home/nathan/.rvm/gems/ruby-1.9.3-p547/gems/contentful_middleman-1.0.3/lib/contentful_middleman/commands/contentful.rb:8:in `require': cannot load such file -- Contentful_middleman/import_task (LoadError)
	from /home/nathan/.rvm/gems/ruby-1.9.3-p547/gems/contentful_middleman-1.0.3/lib/contentful_middleman/commands/contentful.rb:8:in `<top (required)>'
	from /home/nathan/.rvm/gems/ruby-1.9.3-p547/gems/contentful_middleman-1.0.3/lib/contentful_middleman.rb:5:in `require'
	from /home/nathan/.rvm/gems/ruby-1.9.3-p547/gems/contentful_middleman-1.0.3/lib/contentful_middleman.rb:5:in `<top (required)>'
	from /home/nathan/.rvm/gems/ruby-1.9.3-p547@global/gems/bundler-1.7.2/lib/bundler/runtime.rb:76:in `require'
	from /home/nathan/.rvm/gems/ruby-1.9.3-p547@global/gems/bundler-1.7.2/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
	from /home/nathan/.rvm/gems/ruby-1.9.3-p547@global/gems/bundler-1.7.2/lib/bundler/runtime.rb:72:in `each'
	from /home/nathan/.rvm/gems/ruby-1.9.3-p547@global/gems/bundler-1.7.2/lib/bundler/runtime.rb:72:in `block in require'
	from /home/nathan/.rvm/gems/ruby-1.9.3-p547@global/gems/bundler-1.7.2/lib/bundler/runtime.rb:61:in `each'
	from /home/nathan/.rvm/gems/ruby-1.9.3-p547@global/gems/bundler-1.7.2/lib/bundler/runtime.rb:61:in `require'
	from /home/nathan/.rvm/gems/ruby-1.9.3-p547@global/gems/bundler-1.7.2/lib/bundler.rb:133:in `require'
	from /home/nathan/.rvm/gems/ruby-1.9.3-p547/gems/middleman-core-3.3.10/lib/middleman-core/load_paths.rb:37:in `setup_load_paths'
	from /home/nathan/.rvm/gems/ruby-1.9.3-p547/gems/middleman-core-3.3.10/bin/middleman:10:in `<top (required)>'
	from /home/nathan/.rvm/gems/ruby-1.9.3-p547/bin/middleman:23:in `load'
	from /home/nathan/.rvm/gems/ruby-1.9.3-p547/bin/middleman:23:in `<main>'
	from /home/nathan/.rvm/gems/ruby-1.9.3-p547/bin/ruby_executable_hooks:15:in `eval'
	from /home/nathan/.rvm/gems/ruby-1.9.3-p547/bin/ruby_executable_hooks:15:in `<main>'
FAIL: 1
```

**Comment by madtrick** [comment]
Hi, that was fixed on this PR https://github.com/contentful-labs/contentful_middleman/pull/14 and it should be included on the next release (which should happen soon)

**Comment by madtrick** [comment]
We have just released a new version of the gem which includes a fix to this issue
