### ISSUE TITLE
`map_entry': undefined method `id' for "add-on":String

### ISSUE THREAD

**Issue by Naatan** [contentful-labs/contentful_middleman#17]
This one I haven't found a workaround for yet. I've just imported some content into Contentful and am now trying to load it into Middleman, running `middleman contentful`.

My config:

```
contentful_space = {komodo: ENV['CONTENTFUL_SPACE']}
contentful_token = ENV['CONTENTFUL_TOKEN']

activate :contentful do |cntf|
  cntf.space         = contentful_space
  cntf.access_token  = contentful_token
  cntf.cda_query     = { content_type: '2wKn6yEnZewu2SCCkus4as' }
  cntf.content_types = { posts: '2wKn6yEnZewu2SCCkus4as' }
end
```

The full error stack:

```
$ middleman contentful                                                                       [11:26:04]
== LiveReload is waiting for a browser to connect
/home/nathan/.rvm/gems/ruby-1.9.3-p547/gems/contentful_middleman-1.0.3/lib/contentful_middleman/mappers/base.rb:10:in `map_entry': undefined method `id' for "add-on":String (NoMethodError)
	from /home/nathan/.rvm/gems/ruby-1.9.3-p547/gems/contentful_middleman-1.0.3/lib/contentful_middleman/mappers/base.rb:36:in `block in map_array'
	from /home/nathan/.rvm/gems/ruby-1.9.3-p547/gems/contentful_middleman-1.0.3/lib/contentful_middleman/commands/context.rb:31:in `block in map'
	from /home/nathan/.rvm/gems/ruby-1.9.3-p547/gems/contentful_middleman-1.0.3/lib/contentful_middleman/commands/context.rb:29:in `map'
	from /home/nathan/.rvm/gems/ruby-1.9.3-p547/gems/contentful_middleman-1.0.3/lib/contentful_middleman/commands/context.rb:29:in `map'
	from /home/nathan/.rvm/gems/ruby-1.9.3-p547/gems/contentful_middleman-1.0.3/lib/contentful_middleman/mappers/base.rb:35:in `map_array'
	from /home/nathan/.rvm/gems/ruby-1.9.3-p547/gems/contentful_middleman-1.0.3/lib/contentful_middleman/mappers/base.rb:21:in `map_field'
	from /home/nathan/.rvm/gems/ruby-1.9.3-p547/gems/contentful_middleman-1.0.3/lib/contentful_middleman/mappers/base.rb:11:in `block in map_entry'
	from /home/nathan/.rvm/gems/ruby-1.9.3-p547/gems/contentful_middleman-1.0.3/lib/contentful_middleman/mappers/base.rb:11:in `each'
	from /home/nathan/.rvm/gems/ruby-1.9.3-p547/gems/contentful_middleman-1.0.3/lib/contentful_middleman/mappers/base.rb:11:in `map_entry'
	from /home/nathan/.rvm/gems/ruby-1.9.3-p547/gems/contentful_middleman-1.0.3/lib/contentful_middleman/mappers/base.rb:5:in `map'
	from /home/nathan/.rvm/gems/ruby-1.9.3-p547/gems/contentful_middleman-1.0.3/lib/contentful_middleman/import_task.rb:32:in `block in local_data_files'
	from /home/nathan/.rvm/gems/ruby-1.9.3-p547/gems/contentful-0.5.0/lib/contentful/resource/array_like.rb:15:in `each'
	from /home/nathan/.rvm/gems/ruby-1.9.3-p547/gems/contentful-0.5.0/lib/contentful/resource/array_like.rb:15:in `each_item'
	from /home/nathan/.rvm/gems/ruby-1.9.3-p547/gems/contentful_middleman-1.0.3/lib/contentful_middleman/import_task.rb:27:in `map'
	from /home/nathan/.rvm/gems/ruby-1.9.3-p547/gems/contentful_middleman-1.0.3/lib/contentful_middleman/import_task.rb:27:in `local_data_files'
	from /home/nathan/.rvm/gems/ruby-1.9.3-p547/gems/contentful_middleman-1.0.3/lib/contentful_middleman/import_task.rb:14:in `run'
	from /home/nathan/.rvm/gems/ruby-1.9.3-p547/gems/contentful_middleman-1.0.3/lib/contentful_middleman/commands/contentful.rb:48:in `block in contentful'
	from /home/nathan/.rvm/gems/ruby-1.9.3-p547/gems/contentful_middleman-1.0.3/lib/contentful_middleman/commands/contentful.rb:46:in `each'
	from /home/nathan/.rvm/gems/ruby-1.9.3-p547/gems/contentful_middleman-1.0.3/lib/contentful_middleman/commands/contentful.rb:46:in `reduce'
	from /home/nathan/.rvm/gems/ruby-1.9.3-p547/gems/contentful_middleman-1.0.3/lib/contentful_middleman/commands/contentful.rb:46:in `contentful'
	from /home/nathan/.rvm/gems/ruby-1.9.3-p547/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /home/nathan/.rvm/gems/ruby-1.9.3-p547/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /home/nathan/.rvm/gems/ruby-1.9.3-p547/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /home/nathan/.rvm/gems/ruby-1.9.3-p547/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /home/nathan/.rvm/gems/ruby-1.9.3-p547/gems/middleman-core-3.3.10/lib/middleman-core/cli.rb:72:in `method_missing'
	from /home/nathan/.rvm/gems/ruby-1.9.3-p547/gems/thor-0.19.1/lib/thor/command.rb:29:in `run'
	from /home/nathan/.rvm/gems/ruby-1.9.3-p547/gems/thor-0.19.1/lib/thor/command.rb:126:in `run'
	from /home/nathan/.rvm/gems/ruby-1.9.3-p547/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /home/nathan/.rvm/gems/ruby-1.9.3-p547/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /home/nathan/.rvm/gems/ruby-1.9.3-p547/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /home/nathan/.rvm/gems/ruby-1.9.3-p547/gems/middleman-core-3.3.10/lib/middleman-core/cli.rb:20:in `start'
	from /home/nathan/.rvm/gems/ruby-1.9.3-p547/gems/middleman-core-3.3.10/bin/middleman:18:in `<top (required)>'
	from /home/nathan/.rvm/gems/ruby-1.9.3-p547/bin/middleman:23:in `load'
	from /home/nathan/.rvm/gems/ruby-1.9.3-p547/bin/middleman:23:in `<main>'
	from /home/nathan/.rvm/gems/ruby-1.9.3-p547/bin/ruby_executable_hooks:15:in `eval'
	from /home/nathan/.rvm/gems/ruby-1.9.3-p547/bin/ruby_executable_hooks:15:in `<main>'
FAIL: 1
```

I do not have an `add-on` field in my content_type.

**Comment by madtrick** [comment]
@Naatan I found the issue and it shouldn't be difficult to solve it. Will be back to you once fixed

**Comment by madtrick** [comment]
We have just released a new version of the gem that fixes this issue. Please try again and now it should work

**Comment by fkamras** [comment]
I see this is an old issue, but I got the same error on the dl/upgrade-to-v4 branch.
I tried switching to v4-1.x-stable but same issue.
It happens on a text field with a dropdown.

**Comment by dlitvakb** [comment]
Hey @fkamras,

Can you open a ticket in our support system, and ask for me?

Please include in the ticket the `activate :contentful` block as you have it in your setup (including Space ID and Access Token).

Cheers
